"""add missing crop columns

Revision ID: 4b2e8fcad91e
Revises: 001
Create Date: 2026-02-21 15:15:47.967510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b2e8fcad91e'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analyses', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               comment='pending | processing | completed | failed')
    op.alter_column('analyses', 'input_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Raw input snapshot',
               existing_nullable=True)
    op.alter_column('analyses', 'results',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Analysis output',
               existing_nullable=True)
    op.alter_column('analyses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('analyses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_analyses_status'), 'analyses', ['status'], unique=False)
    op.add_column('crops', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('crops', sa.Column('optimal_temp_min', sa.Float(), nullable=True, comment='°C'))
    op.add_column('crops', sa.Column('optimal_temp_max', sa.Float(), nullable=True, comment='°C'))
    op.add_column('crops', sa.Column('water_requirement', sa.Float(), nullable=True, comment='mm per season'))
    op.add_column('crops', sa.Column('optimal_ph_min', sa.Float(), nullable=True))
    op.add_column('crops', sa.Column('optimal_ph_max', sa.Float(), nullable=True))
    op.alter_column('crops', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('crops', 'scientific_name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('crops', 'category',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               comment='e.g. cereal, pulse, oilseed',
               existing_nullable=True)
    op.alter_column('crops', 'growth_duration',
               existing_type=sa.INTEGER(),
               comment='Days from sowing to harvest',
               existing_nullable=True)
    op.alter_column('crops', 'preferred_soil_types',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.String(length=255),
               comment='Comma-separated',
               existing_nullable=True)
    op.alter_column('crops', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('crops', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('crops_name_key', 'crops', type_='unique')
    op.create_index(op.f('ix_crops_category'), 'crops', ['category'], unique=False)
    op.create_index(op.f('ix_crops_name'), 'crops', ['name'], unique=True)
    op.drop_column('crops', 'min_ph')
    op.drop_column('crops', 'min_rainfall')
    op.drop_column('crops', 'max_rainfall')
    op.drop_column('crops', 'min_temperature')
    op.drop_column('crops', 'max_ph')
    op.drop_column('crops', 'nitrogen_requirement')
    op.drop_column('crops', 'max_temperature')
    op.drop_column('crops', 'phosphorus_requirement')
    op.drop_column('crops', 'potassium_requirement')
    op.alter_column('lands', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('lands', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('lands', 'size',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               comment='Size in hectares')
    op.alter_column('lands', 'soil_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('lands', 'organic_matter',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Percentage',
               existing_nullable=True)
    op.alter_column('lands', 'nitrogen',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='kg/ha',
               existing_nullable=True)
    op.alter_column('lands', 'phosphorus',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='kg/ha',
               existing_nullable=True)
    op.alter_column('lands', 'potassium',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='kg/ha',
               existing_nullable=True)
    op.alter_column('lands', 'irrigation_available',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('lands', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('lands', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('lands', 'water_source')
    op.add_column('market_data', sa.Column('price', sa.Float(), nullable=False, comment='₹ per quintal'))
    op.add_column('market_data', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('market_data', sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('market_data', 'unit',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('market_data', 'market_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('market_data', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('market_data', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('market_data', 'source')
    op.drop_column('market_data', 'date_recorded')
    op.drop_column('market_data', 'price_per_unit')
    op.add_column('recommendations', sa.Column('confidence_level', sa.Float(), nullable=True, comment='0–1'))
    op.add_column('recommendations', sa.Column('notes', sa.Text(), nullable=True))
    op.alter_column('recommendations', 'suitability_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               comment='0–100')
    op.alter_column('recommendations', 'predicted_yield',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='tons/ha',
               existing_nullable=True)
    op.alter_column('recommendations', 'estimated_profit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='₹ per acre',
               existing_nullable=True)
    op.alter_column('recommendations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('recommendations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_recommendations_crop_id'), 'recommendations', ['crop_id'], unique=False)
    op.drop_column('recommendations', 'details')
    op.drop_column('recommendations', 'confidence')
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('recommendations', sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('recommendations', sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_recommendations_crop_id'), table_name='recommendations')
    op.alter_column('recommendations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('recommendations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('recommendations', 'estimated_profit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='₹ per acre',
               existing_nullable=True)
    op.alter_column('recommendations', 'predicted_yield',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='tons/ha',
               existing_nullable=True)
    op.alter_column('recommendations', 'suitability_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               comment=None,
               existing_comment='0–100')
    op.drop_column('recommendations', 'notes')
    op.drop_column('recommendations', 'confidence_level')
    op.add_column('market_data', sa.Column('price_per_unit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('market_data', sa.Column('date_recorded', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('market_data', sa.Column('source', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.alter_column('market_data', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('market_data', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('market_data', 'market_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('market_data', 'unit',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('market_data', 'recorded_at')
    op.drop_column('market_data', 'location')
    op.drop_column('market_data', 'price')
    op.add_column('lands', sa.Column('water_source', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.alter_column('lands', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('lands', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('lands', 'irrigation_available',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('lands', 'potassium',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='kg/ha',
               existing_nullable=True)
    op.alter_column('lands', 'phosphorus',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='kg/ha',
               existing_nullable=True)
    op.alter_column('lands', 'nitrogen',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='kg/ha',
               existing_nullable=True)
    op.alter_column('lands', 'organic_matter',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Percentage',
               existing_nullable=True)
    op.alter_column('lands', 'soil_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('lands', 'size',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               comment=None,
               existing_comment='Size in hectares')
    op.alter_column('lands', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('lands', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.add_column('crops', sa.Column('potassium_requirement', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('crops', sa.Column('phosphorus_requirement', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('crops', sa.Column('max_temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('crops', sa.Column('nitrogen_requirement', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('crops', sa.Column('max_ph', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('crops', sa.Column('min_temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('crops', sa.Column('max_rainfall', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('crops', sa.Column('min_rainfall', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('crops', sa.Column('min_ph', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_crops_name'), table_name='crops')
    op.drop_index(op.f('ix_crops_category'), table_name='crops')
    op.create_unique_constraint('crops_name_key', 'crops', ['name'])
    op.alter_column('crops', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('crops', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('crops', 'preferred_soil_types',
               existing_type=sa.String(length=255),
               type_=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Comma-separated',
               existing_nullable=True)
    op.alter_column('crops', 'growth_duration',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Days from sowing to harvest',
               existing_nullable=True)
    op.alter_column('crops', 'category',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='e.g. cereal, pulse, oilseed',
               existing_nullable=True)
    op.alter_column('crops', 'scientific_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('crops', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('crops', 'optimal_ph_max')
    op.drop_column('crops', 'optimal_ph_min')
    op.drop_column('crops', 'water_requirement')
    op.drop_column('crops', 'optimal_temp_max')
    op.drop_column('crops', 'optimal_temp_min')
    op.drop_column('crops', 'description')
    op.drop_index(op.f('ix_analyses_status'), table_name='analyses')
    op.alter_column('analyses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('analyses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('analyses', 'results',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Analysis output',
               existing_nullable=True)
    op.alter_column('analyses', 'input_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Raw input snapshot',
               existing_nullable=True)
    op.alter_column('analyses', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               comment=None,
               existing_comment='pending | processing | completed | failed')
    # ### end Alembic commands ###
